#! /usr/bin/env python3.10
from controllers import show_tasks
from printer import *


def say_hi() -> AllowedCommands:
    user_answer = print_hi_message()
    is_normal_answer, command = False, None
    while not is_normal_answer:
        command = detect_command(user_answer)
        if command:
            is_normal_answer = True
        else:
            user_answer = print_hi_error_message()
    return command


def main():
    """Программа возвращает задачи на текущий день и сохраняет их в историю"""
    command = say_hi()
    match command.value:
        case AllowedCommands.STATS.value:
            print("Обработчик статистики")
        case AllowedCommands.ADD_TASKS.value:
            print("Обработчик добавления команды")
        case AllowedCommands.EDIT_TASKS.value:
            print("Обработчик редактирования команды")
        case AllowedCommands.SHOW_TODAY_TASKS.value:
            show_tasks.today()
        case AllowedCommands.SHOW_TASKS_BY_DATE.value:
            show_tasks.by_date()
        case _:
            print('err')


if __name__ == "__main__":
    main()
